---
title: "00_Preprocess_Data"
author: "Connor Quiroz"
date: "2025-03-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(cowplot)
library(arrow)
library(countrycode)
library(exploreARTIS)
```

```{r read in data}
# Specify the folder path
folder_path <- "../data/full consumption/consumption/"

# List all CSV files in the folder
csv_files <- list.files(path = folder_path, pattern = "*.csv", full.names = TRUE)

# Create empty data frame
consumption_full <- data.frame()

# Use a loop to read the files and bind them together
#Takes a long time to run
for (i in csv_files) {
  # Read the CSV file
  yearly_data <- read_csv(i)
  consumption_full <- bind_rows(consumption_full, yearly_data)
}

consumption_full <- consumption_full %>%
  filter(
    # Use HS96 from 1996-2003 (inclusive)
    ((hs_version == "HS96") & (year <= 2003)) |
      # Use HS02 from 2004-2009 (inclusive)
      ((hs_version == "HS02") & (year >= 2004 & year <= 2009)) |
      # Use HS07 from 2010-2012 (inclusive)
      ((hs_version == "HS07") & (year >= 2010 & year <= 2012)) |
      # Use HS12 from 2013-2019 (inclusive)
      ((hs_version == "HS12") & (year >= 2013 & year <= 2020))
  ) 

# Save to .parquet file
write_parquet(consumption_full, "../output/consumption_full.parquet")
```

```{r convert FAO data to .parquet}
# Read in FAO consumer data
fao_food <- read_csv("../data/FoodBalanceSheets_E_All_Data/FoodBalanceSheets_E_All_Data.csv")

# Save to .parquet
write_parquet(fao_food, "../output/fao_food.parquet")

# Read in FAO historical data
fao_historical <- read_csv("../data/FoodBalanceSheetsHistoric_E_All_Data/FoodBalanceSheetsHistoric_E_All_Data.csv")

# Save to .parquet
write_parquet(fao_historical, "../output/fao_historical.parquet")
```

