---
title: "02_results"
author: "Jessica Gephart"
date: "2025-09-05"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(cowplot)
library(exploreARTIS)
library(cowplot)
```

```{r load data}
aquatic_reliance <- read.csv("../data/fao_aquatic_reliance_source.csv")
aquatic_fbs <- read.csv("../data/fao_fbs_aquatic_source.csv")
```

```{r}
aquatic_reliance %>%
  filter(year == 2020) %>%
  mutate(habitat_method = paste(habitat, method)) %>%
  plot_bar(bar_group = "iso3c", fill_type = "habitat_method", 
           value = "aquatic_source_prop")

aquatic_reliance %>%
  filter(year == 2020) %>%
  mutate(habitat_method = paste(habitat, method)) %>%
  plot_bar(bar_group = "iso3c", fill_type = "consumption_source", 
           value = "aquatic_source_prop")
```

```{r}
aquatic_reliance %>%
  filter(year == 2020, consumption_source == "foreign") %>%
  mutate(habitat_method = paste(habitat, method)) %>%
  plot_bar(bar_group = "iso3c", fill_type = "habitat_method", 
           value = "aquatic_source_prop", 
           top_n = 30)
```


```{r}
aquatic_reliance %>%
  filter(year == 2020) %>%
  mutate(habitat_method = paste(habitat, method)) %>%
  plot_bar(bar_group = "iso3c", fill_type = "habitat_method",
           value = "prop_animal_protein", 
           top_n = 30)


aquatic_reliance %>%
  filter(year == 2020) %>%
  mutate(habitat_method = paste(habitat, method)) %>%
  filter(habitat_method == "marine capture") %>%
  plot_bar(bar_group = "iso3c", fill_type = "habitat_method",
           value = "prop_animal_protein", 
           top_n = 30)
```

```{r global mean reliance}
(aa_reliance_mean_global_trends <- aquatic_reliance %>%
  group_by(year, iso3c, data_source) %>%
  summarize(prop_animal_protein = sum(prop_animal_protein, na.rm = TRUE)) %>%
  group_by(year, data_source) %>%
  summarize(prop_animal_protein = 100 * mean(prop_animal_protein, na.rm = TRUE)) %>%
  filter(!(year %in% c(2010, 2011, 2012, 2013) & data_source == "old FBS")) %>%
  ggplot(aes(x = year, y = prop_animal_protein, color = data_source)) +
           geom_line(size = 1.1) +
  scale_color_manual(values = artis_palette(3)) +
  theme_light() +
  labs(x = "",
       y = "Global mean AA reliance (%)",
       color = "Data source") +
  theme(legend.position = "bottom"))

ggsave("../images/aa_reliance_mean_global_trends.jpg", plot = aa_reliance_mean_global_trends, device = "jpeg", units = "in", width = 5, height = 4)
```

```{r}
(aa_reliance_mean_regional_trends <- aquatic_reliance %>%
  group_by(year, iso3c, data_source) %>%
  summarize(prop_animal_protein = sum(prop_animal_protein, na.rm = TRUE)) %>%
  add_region(col = "iso3c", region.col.name = "region") %>%
  group_by(year, region, data_source) %>%
  summarize(prop_animal_protein = 100 * mean(prop_animal_protein, na.rm = TRUE)) %>%
  filter(!(year %in% c(2010, 2011, 2012, 2013) & data_source == "old FBS"),
         !is.na(region)) %>%
  ggplot(aes(x = year, y = prop_animal_protein, color = region, linetype = data_source)) +
           geom_line(size = 1.1) +
  scale_color_manual(values = artis_palette(6)) +
  theme_light() +
  theme(legend.position = "bottom",
        legend.key.size = unit(0.2, 'cm'),
        legend.text = element_text(size = 6),
        legend.title = element_text(size = 8)) +
  labs(x = "",
       y = "Regional mean AA reliance (%)",
       color = "Region",
       linetype = "Data source"))

ggsave("../images/aa_reliance_mean_regional_trends.jpg", plot = aa_reliance_mean_regional_trends, device = "jpeg", units = "in", width = 5, height = 4)

aquatic_reliance %>%
  
  add_region(col = "iso3c", region.col.name = "region") %>%
  filter(region == "Oceania") %>%

```

```{r}
(aa_reliance_multiple_trends <- aquatic_reliance %>%
  group_by(year, iso3c, data_source, habitat, method, consumption_source) %>%
  summarize(prop_animal_protein = sum(prop_animal_protein, na.rm = TRUE)) %>%
  group_by(year, data_source, habitat, method, consumption_source) %>%
  summarize(prop_animal_protein = 100 * mean(prop_animal_protein, na.rm = TRUE)) %>%
  filter(!(year %in% c(2010, 2011, 2012, 2013) & data_source == "old FBS"),
         !is.na(consumption_source)) %>%
  ggplot(aes(x = year, y = prop_animal_protein, color = data_source, linetype = consumption_source)) +
           geom_line(size = 0.9) +
  scale_color_manual(values = artis_palette(3)) +
  theme_light() +
  facet_wrap(habitat ~ method) +
  theme(legend.position = "bottom",
        axis.text = element_text(size = 6,
                                 angle = 45),
        legend.title = element_text(size = 7),
        legend.text = element_text(size = 5)) +
  labs(linetype = "Consumption source",
       color = "Data source",
       x = "",
       y = "Aquatic animal Reliance (%)"))

ggsave("../images/aa_reliance_multiple_trends.jpg", plot = aa_reliance_multiple_trends, device = "jpeg", units = "in", width = 5, height = 4)
```

```{r}
source("../R/create_map.R")

(a <- aquatic_reliance %>%
  filter(year == 2020) %>%
  group_by(iso3c) %>%
  summarize(prop_animal_protein = 100 * sum(prop_animal_protein)) %>%
  create_map(fill = "prop_animal_protein", country.col.name = "iso3c") +
  labs(fill = "AA reliance (%)",
       tag = "A") +
    theme(legend.key.size = unit(0.3, 'cm'),
          legend.title = element_text(size = 8),
          legend.text = element_text(size = 5.5)))

(b <- aquatic_reliance %>%
  filter(method == "capture",
         habitat == "marine",
         year == 2020) %>%
  group_by(iso3c) %>%
  summarize(prop_animal_protein = 100 * sum(prop_animal_protein)) %>%
  create_map(fill = "prop_animal_protein", country.col.name = "iso3c") +
  labs(fill = "AA marine capture reliance (%)",
       tag = "B") +
    theme(legend.key.size = unit(0.3, 'cm'),
          legend.title = element_text(size = 8),
          legend.text = element_text(size = 5.5)))


(aa_reliance_chloropleth <- plot_grid(a, b, align = "v"))
  

ggsave("../images/aa_reliance_chloropleth.jpg", plot = aa_reliance_chloropleth, device = "jpeg", units = "in", width = 5, height = 2)
```
  
```{r}
(aa_reliance_histogram <- aquatic_reliance %>%
  filter(year == 2020) %>%
   mutate(prop_animal_protein = prop_animal_protein * 100) %>%
  ggplot(aes(x = prop_animal_protein, fill = consumption_source)) +
  geom_histogram(alpha = 0.5, color = "black",position = "identity") +
  facet_wrap(habitat ~ method) +
  theme_light() +
  theme(legend.position = "bottom") +
  scale_fill_manual(values = artis_palette(3)) +
  labs(x = "AA reliance (%)", y = "Number of countries",
       fill = "Consumption source"))

ggsave("../images/aa_reliance_histogram.jpg", plot = aa_reliance_histogram, device = "jpeg", units = "in", width = 5, height = 4)
```

```{r summary stats}
aquatic_reliance %>%
  group_by(year, iso3c, data_source) %>%
  summarize(prop_animal_protein = sum(prop_animal_protein, na.rm = TRUE)) %>%
  group_by(year, data_source) %>%
  summarize(prop_animal_protein = 100 * mean(prop_animal_protein, na.rm = TRUE)) %>%
  filter(year == 2020)
```

